name: Build and Deploy PiDrive

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      BACKEND_IMAGE_NAME: pidrive-backend
      FRONTEND_IMAGE_NAME: pidrive-frontend
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: apps/frontend/package-lock.json
      - name: Install frontend dependencies
        run: cd apps/frontend && npm ci
      - name: Lint frontend
        run: cd apps/frontend && npm run lint
      - name: Build frontend
        run: cd apps/frontend && npm run build

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: pip
          cache-dependency-path: apps/backend/requirements.txt
      - name: Install backend dependencies
        run: cd apps/backend && pip install -r requirements.txt

      - uses: docker/setup-buildx-action@v3

      - run: docker build -t ${{ env.BACKEND_IMAGE_NAME }}:latest -f apps/backend/Dockerfile apps/backend
      - run: docker build --build-arg NEXT_PUBLIC_API_URL="http://backend:4000" --build-arg NEXT_PUBLIC_SITE_URL="http://localhost:3000" -t ${{ env.FRONTEND_IMAGE_NAME }}:latest -f apps/frontend/Dockerfile apps/frontend

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Push to Docker Hub
        run: |
          VERSION=${{ github.sha }}
          docker tag ${{ env.BACKEND_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:latest
          docker tag ${{ env.BACKEND_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }}:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.BACKEND_IMAGE_NAME }} --all-tags
          docker tag ${{ env.FRONTEND_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:latest
          docker tag ${{ env.FRONTEND_IMAGE_NAME }}:latest ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }}:$VERSION
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ env.FRONTEND_IMAGE_NAME }} --all-tags
